"""The coupling alpha as a boundary observable: alpha = kappa^2/g^2 is a fixed
multiple of C_J / C_T, and alpha_* becomes (C_J/C_T)_* = 8/(d^2 (d+1)).

What is derived here, and what is quoted
----------------------------------------
[1] DERIVED: from the action

        S = (1/2 kappa^2) int sqrt(-g) (R + d(d-1)/L^2) - (1/4 g^2) int sqrt(-g) F^a F^a

    the Ricci-form field equation is, in D = d+1 bulk dimensions with L = 1,

        R_MN + d g_MN = alpha (F_MP F_N^P - F^2 g_MN / (2(d-1))),   alpha = kappa^2/g^2,

    which for d = 4 is the project's R_MN + 4 g_MN = alpha(FF - F^2 g/6): so
    alpha is the ratio of the Einstein-Hilbert to the Yang-Mills coefficient
    with exactly these normalisations (no stray 2s).

[2] QUOTED (literature normalisations, Osborn-Petkou conventions
    <T T> = C_T I_{ij,kl}/x^{2d}, <J J> = C_J I_{ij}/x^{2(d-1)}):

        C_T = (d+1)/(d-1) * Gamma(d+1) / (pi^{d/2} Gamma(d/2)) * L^{d-1} / kappa^2
              [Einstein gravity; e.g. Buchel-Escobedo-Myers-Paulos-Sinha-Smolkin
               arXiv:0911.4257 eq. (3.15) at lambda_GB = 0, action (2.1),
               with l_P^{d-1} = 8 pi G = kappa^2]
        C_J = (d-2) Gamma(d) / (2 pi^{d/2} Gamma(d/2)) * L^{d-3} / g^2
              [Maxwell -(1/4g^2) F^2; Freedman-Mathur-Matusis-Rastelli
               hep-th/9804058; Chowdhury-Raju-Sachdev-Singh-Strack 1210.4166]

    For a non-abelian field these are per generator with Tr normalised so
    that the kinetic term is -(1/4g^2) F^a F^a as above (i.e. the U(1)
    subgroup generated by T^3 carries the abelian formula verbatim, which is
    the current the background field B couples to).

[3] DERIVED from [1]+[2]:

        C_J / C_T = (d-1)(d-2) / (2 d (d+1)) * alpha          (L = 1)
        alpha_*(d) = 16 / (d(d-1)(d-2))   =>   (C_J/C_T)_* = 8 / (d^2 (d+1))

    d = 4: (C_J/C_T)_* = 1/10;  d = 3: 2/9 (Wong's gamma_* = 3/4, gamma = 2/alpha).

Status.  [2] is a citation here, not a derivation.  It is anchored in
`central_charge_anchor.py` (the N = 2 Ward identities fix C_J(SU(2)_R)/C_T =
3/80, reproduced by the holographic map at Romans' alpha_SUSY = 1/4, and the
cited normalisations are re-derived there from the cited equations) and in
`central_charge_anchor_d3.py` (the d = 3 counterpart, C_R/C_T = 1/6).

Run:  uv run python -m backreaction.derivations.dk_central_charges
"""

import time

import sympy as sp

T0 = time.time()
CHECKS = {}


def log(msg):
    print(f"[{time.time() - T0:6.1f}s] {msg}", flush=True)


def check(name, ok, detail=""):
    CHECKS[name] = bool(ok)
    log(f"  [{'PASS' if ok else 'FAIL'}] {name}{('  ' + detail) if detail else ''}")


d = sp.Symbol("d", positive=True, integer=True)
alpha, kappa2, g2, L = sp.symbols("alpha kappa2 g2 L", positive=True)


def main():
    # ---------------------------------------------------------------------------
    # [1] trace reversal in D = d + 1 dimensions
    # ---------------------------------------------------------------------------
    log("[1] Ricci form of the Einstein equation with the Yang-Mills stress tensor")
    # Einstein equation from S:  (1/2kappa^2)(G_MN - d(d-1)/2 g_MN) = (1/2 g^2) T~_MN,
    # T~_MN = F_MP F_N^P - (1/4) g_MN F^2   (from varying -(1/4g^2) F^2 wrt g^MN).
    # Take the trace with g^MN g_MN = D = d+1 and write R_MN = a R g + b g + c FF + e F^2 g.
    R, F2, FF = sp.symbols("R F2 FF")  # scalars: R, F^2, and the FF_MN entry (formal)
    D = d + 1
    # trace of  R_MN - R/2 g - d(d-1)/2 g = alpha (FF - F2/4 g):
    #   R - D R/2 - D d(d-1)/2 = alpha (F2 - D F2/4)
    Rsol = sp.solve(
        sp.Eq(R - D * R / 2 - D * d * (d - 1) / 2, alpha * (F2 - D * F2 / 4)), R
    )[0]
    # then R_MN = R/2 g + d(d-1)/2 g + alpha(FF - F2/4 g); collect the g_MN coefficient
    g_coeff = sp.simplify(Rsol / 2 + d * (d - 1) / 2 - alpha * F2 / 4)
    g_coeff_expected = -d - alpha * F2 / (2 * (d - 1))
    check(
        "[1] R_MN + d g_MN = alpha (F_MP F_N^P - F^2 g_MN / (2(d-1))) in general d",
        sp.simplify(g_coeff - g_coeff_expected) == 0,
        f"g_MN coefficient = {sp.factor(g_coeff)}",
    )
    check(
        "[1] d = 4 reproduces the project convention R_MN + 4 g_MN = alpha(FF - F^2 g/6)",
        sp.simplify(g_coeff.subs(d, 4) - (-4 - alpha * F2 / 6)) == 0,
    )

    # ---------------------------------------------------------------------------
    # [2] the quoted central charges
    # ---------------------------------------------------------------------------
    C_T = (
        (d + 1)
        / (d - 1)
        * sp.gamma(d + 1)
        / (sp.pi ** (d / 2) * sp.gamma(d / 2))
        * L ** (d - 1)
        / kappa2
    )
    C_J = (
        (d - 2)
        * sp.gamma(d)
        / (2 * sp.pi ** (d / 2) * sp.gamma(d / 2))
        * L ** (d - 3)
        / g2
    )
    log("[2] C_T, C_J quoted (Osborn-Petkou conventions, Einstein + Maxwell)")
    # sanity: N = 4 SYM, L^3/kappa^2 = L^3/(8 pi G_5) with L^3/G_5 = 2 N^2/pi  =>  C_T = 10 N^2/pi^4
    Nc = sp.Symbol("N", positive=True)
    CT4 = C_T.subs(d, 4).subs(kappa2, 8 * sp.pi * L**3 * sp.pi / (2 * Nc**2))
    check(
        "[2] sanity: d = 4 with L^3/G_5 = 2N^2/pi gives C_T = 10 N^2/pi^4 (= 40c/pi^4, c = N^2/4)",
        sp.simplify(CT4 - 10 * Nc**2 / sp.pi**4) == 0,
    )

    # ---------------------------------------------------------------------------
    # [3] the ratio and the critical value
    # ---------------------------------------------------------------------------
    ratio = sp.simplify((C_J / C_T).subs({kappa2: alpha * g2, L: 1}))
    ratio_expected = (d - 1) * (d - 2) / (2 * d * (d + 1)) * alpha
    check(
        "[3] C_J/C_T = (d-1)(d-2)/(2d(d+1)) alpha  (L = 1)",
        sp.simplify(sp.gammasimp(ratio - ratio_expected)) == 0,
        f"ratio = {sp.simplify(sp.gammasimp(ratio))}",
    )
    alpha_star = 16 / (d * (d - 1) * (d - 2))
    cj_ct_star = sp.simplify(ratio_expected.subs(alpha, alpha_star))
    check(
        "[3] (C_J/C_T)_* = 8 / (d^2 (d+1))",
        sp.simplify(cj_ct_star - 8 / (d**2 * (d + 1))) == 0,
        f"(C_J/C_T)_* = {cj_ct_star}",
    )
    vals = {dd: sp.nsimplify(cj_ct_star.subs(d, dd)) for dd in (3, 4, 5, 6)}
    log(f"      (C_J/C_T)_* for d = 3..6: {vals}")
    check("[3] d = 4: (C_J/C_T)_* = 1/10", vals[4] == sp.Rational(1, 10))
    check(
        "[3] d = 3: (C_J/C_T)_* = 2/9  (Wong: gamma = 2/alpha, gamma_* = 3/4)",
        vals[3] == sp.Rational(2, 9)
        and sp.simplify(2 / alpha_star.subs(d, 3)) == sp.Rational(3, 4),
    )
    # the inverse map:  alpha = 2d(d+1)/((d-1)(d-2)) * C_J/C_T
    inv = sp.simplify(2 * d * (d + 1) / ((d - 1) * (d - 2)) * ratio_expected)
    check("[3] alpha = 2d(d+1)/((d-1)(d-2)) * C_J/C_T", sp.simplify(inv - alpha) == 0)

    log("")
    log("SUMMARY")
    log(
        "  alpha = kappa^2/g^2 = 2d(d+1)/((d-1)(d-2)) * C_J/C_T   [d = 4: alpha = 20/3 * C_J/C_T]"
    )
    log(
        "  alpha_* = 16/(d(d-1)(d-2))  <=>  (C_J/C_T)_* = 8/(d^2(d+1))  [d = 4: 1/10; d = 3: 2/9]"
    )
    log(
        "  status: C_T, C_J normalisations quoted (0911.4257, 9804058/1210.4166); anchored by central_charge_anchor.py (d = 4) and central_charge_anchor_d3.py (d = 3)"
    )
    nfail = sum(1 for v in CHECKS.values() if not v)
    log(f"{len(CHECKS) - nfail}/{len(CHECKS)} checks passed")
    if nfail:
        raise SystemExit(1)
    log("ALL CHECKS PASSED")


if __name__ == "__main__":
    main()
