"""Provenance of the auto-generated modules in `backreaction/systems/`.

These modules are SymPy output written to disk by the generators in
`backreaction/derivations/` and imported by the numerics.  They are the seam
between the symbolic and numeric halves of the project; without these checks a
hand edit and a stale regeneration would both look exactly like a clean tree.

Three checks of increasing strength and cost:

* `test_content_matches_stamp` -- the file has not been edited since it was
  generated.  Milliseconds; fast tier.
* `test_generator_unchanged` -- the generator's code is still the revision
  that produced the file.  Milliseconds.  It digests the parsed AST with
  docstrings stripped, so comment, layout and docstring edits pass and any
  other change asks for a re-run (`generated.code_digest`).  `ast.dump` can
  differ between Python minor versions, so under a version other than the one
  that stamped the file the test skips rather than fails.  Fast tier.
* `test_regenerates_identically` -- actually re-runs the generator into a
  scratch copy of the tree and diffs.  This is the only check that *proves* the
  committed file is current.  Minutes; slow tier.

See `backreaction/generated.py` for the stamp format.
"""

import os
import pathlib
import shutil
import subprocess
import sys

from backreaction import generated
import pytest

PROJECT_ROOT = pathlib.Path(__file__).resolve().parent.parent
BACKREACTION = PROJECT_ROOT / "backreaction"
BK = BACKREACTION / "systems"
DERIVATIONS = BACKREACTION / "derivations"

GENERATED = sorted(p.name for p in BK.glob("*.py") if p.name != "__init__.py")


def test_the_generated_set_is_not_empty():
    """Guard the guard: empty discovery would make every test below vacuous."""
    assert len(GENERATED) >= 9, f"expected the 9 known generated modules, got {GENERATED}"


@pytest.mark.parametrize("name", GENERATED)
def test_has_provenance_block(name):
    fields = generated.read_stamp(BK / name)
    assert fields, (f"{name} carries no provenance block; it should be written by "
                    f"its generator calling generated.stamp()")
    assert fields.get("generator", "").endswith(".py")
    assert len(fields.get("content_sha256", "")) == 64
    assert len(fields.get("generator_code_sha256", "")) == 64


@pytest.mark.parametrize("name", GENERATED)
def test_content_matches_stamp(name):
    ok, detail = generated.check_content(BK / name)
    assert ok, f"{name}: {detail} -- the file was edited after generation"


@pytest.mark.parametrize("name", GENERATED)
def test_generator_unchanged(name):
    ok, detail = generated.check_generator(BK / name, generator_dir=DERIVATIONS)
    if ok is None:
        pytest.skip(f"{name}: {detail}")
    assert ok, f"{name}: {detail}"


@pytest.mark.parametrize("name", GENERATED)
def test_declared_generator_exists_and_agrees_with_the_docstring(name):
    """The stamp and the file's own 'AUTO-GENERATED by ...' header must agree."""
    path = BK / name
    stamped = generated.read_stamp(path)["generator"]
    assert (DERIVATIONS / stamped).exists(), f"{name}: generator {stamped} is missing"
    header = path.read_text().split("\n", 1)[0]
    assert stamped in header, (f"{name}: stamp names {stamped} but the docstring "
                               f"header says {header!r}")


@pytest.mark.slow
@pytest.mark.parametrize("name", GENERATED)
def test_regenerates_identically(name, tmp_path):
    """Re-run the generator in a scratch tree and diff its output.

    `paths.SYSTEMS` resolves relative to wherever the imported `backreaction`
    package physically sits, so the whole package (minus the data/figures
    output dirs, which the generators don't touch) is copied into a scratch
    root and put first on the subprocess's PYTHONPATH; the generator then
    reads and writes consistently inside the scratch tree, leaving the
    committed one untouched.
    """
    committed = BK / name
    generator = generated.read_stamp(committed)["generator"]

    scratch_root = tmp_path / "scratch"
    scratch = scratch_root / "backreaction"
    shutil.copytree(BACKREACTION, scratch,
                    ignore=shutil.ignore_patterns("__pycache__", "data", "figures"))

    env = dict(os.environ)
    # The generator does `from backreaction import paths` etc.; point that
    # import at the scratch copy so it reads and writes consistently inside it.
    env["PYTHONPATH"] = os.pathsep.join(
        [str(scratch_root), str(PROJECT_ROOT / "scripts"), env.get("PYTHONPATH", "")])

    proc = subprocess.run([sys.executable, str(scratch / "derivations" / generator)],
                          capture_output=True, text=True, cwd=PROJECT_ROOT,
                          env=env, check=False)
    assert proc.returncode == 0, (
        f"{generator} failed (rc={proc.returncode}):\n{proc.stdout[-2000:]}\n{proc.stderr[-2000:]}")

    regenerated = scratch / "systems" / name
    assert regenerated.exists(), f"{generator} did not write {name}"

    got_body, _ = generated._split(regenerated)
    want_body, _ = generated._split(committed)
    assert got_body == want_body, (
        f"{name} is STALE: re-running {generator} produces different output than "
        f"the committed file.  Commit the regenerated file (and check the "
        f"published numbers that depend on it).")


def test_gitattributes_keeps_generated_files_byte_exact():
    """content_sha256 hashes raw bytes, so a checkout that rewrote line endings
    (core.autocrlf on Windows) would fail every content check.  `.gitattributes`
    marks the generated modules `-text`; this asserts git still sees that."""
    if shutil.which("git") is None or not (PROJECT_ROOT / ".git").exists():
        pytest.skip("not a git checkout")
    proc = subprocess.run(
        ["git", "check-attr", "text", "--", *(f"backreaction/systems/{n}" for n in GENERATED)],
        cwd=PROJECT_ROOT, capture_output=True, text=True, check=True)
    lines = proc.stdout.strip().splitlines()
    assert len(lines) == len(GENERATED)
    assert all(line.endswith(": text: unset") for line in lines), proc.stdout
