"""AUTO-GENERATED by bc_shift.py -- do not edit.

O(alpha) perturbation of the probe-limit zero-mode operator by a
diagonal G = 0 metric correction (ht, hx, hz, hu) =
(Htt, Hxx, Hzz, Huu), per unit alpha:
    delta B_c = int_0^{u_H} [dP w0'^2 - dQ w0^2] du   (J2 = 1)
"""

import math  # noqa: F401


def dP(u, B, u_H, ht, hx, hz, hu, dht, dhx, dhz, dhu):
    return -1/2*ht*u**3/u_H**4 + (1/2)*ht/u + (1/2)*hu*u**3/u_H**4 - 1/2*hu/u - 1/2*hz*u**3/u_H**4 + (1/2)*hz/u


def dQ(u, B, u_H, ht, hx, hz, hu, dht, dhx, dhz, dhu):
    return (1/2)*B*ht/u + (1/2)*B*hu/u - B*hx/u + (1/2)*B*hz/u

# --- provenance ----------------------------------------------------------
# Written by bc_shift.py; do not edit by hand.  Verified by
# tests/test_generated_systems.py -- see backreaction/generated.py.
# generator:             bc_shift.py
# generator_code_sha256: a19e0801a0efb847b4916993fb43134bb775a0c956c190a72bff9e8f85271b05
# content_sha256:        667af00b9950eefb9e9eae86f98bf1fa48d2f493f12afe0de93b24f3864463f2
# python:                3.14
# --- provenance ----------------------------------------------------------
