"""AUTO-GENERATED by dk_quartic.py -- do not edit.

Per-harmonic induced-field ODE and quartic-kernel weights on the
general diagonal magnetic brane
    ds^2 = -U dt^2 + dr^2/U + e^{2V}(dx^2+dy^2) + e^{2W} dz^2.
Induced field (per rho^2 lambda_G, G || x):
    -(p2 bhat')' + G^2 p1 (bhat - w0^2) = 0,
    p1 = e^{W-2V},  p2 = U e^{W},  p2' = e^{W}(U' + U W').
Kernel weights (measure dr): contact C4 = int p1 w0^4,
exchange X = int p1 bhat w0^2.
"""

import math  # noqa: F401


def p1(r, U, Up, V, Vp, W, Wp, B):
    return math.exp(-2*V + W)


def p2(r, U, Up, V, Vp, W, Wp, B):
    return U*math.exp(W)


def p2p(r, U, Up, V, Vp, W, Wp, B):
    return (U*Wp + Up)*math.exp(W)

# --- provenance ----------------------------------------------------------
# Written by dk_quartic.py; do not edit by hand.  Verified by
# tests/test_generated_systems.py -- see backreaction/generated.py.
# generator:             dk_quartic.py
# generator_code_sha256: 134336aeacfe0c00f7272ea7542aa2fbab5f5a088ecee093554a3de408c5523d
# content_sha256:        5a8cd6b3c14c94b8b46b6dfdc95339fb4f749f5230b1db56cfe27915784163aa
# python:                3.14
# --- provenance ----------------------------------------------------------
