"""AUTO-GENERATED by dk_response.py -- do not edit.

Coupled O(rho^2) lattice response on the D'Hoker-Kraus magnetic brane
  ds^2 = -U dt^2 + dr^2/U + e^{2V}(dx^2+dy^2) + e^{2W} dz^2,  A^3_y=Bx,
per harmonic G || x, even sector (y-parity o U(1) charge flip).
Algebraic gauge H_tt=H_xx=0: (H_yy,H_zz,a_y) second order, (H_rr,H_xr)
algebraic; a_y = transverse abelian mode, b = iG a_y.  Each row:
  field'' = coeff_H . (H_yy,H_zz,a_y) + coeff_dH . (H_yy',H_zz',a_y') + src
src = w0-bilinear condensate source (W0=w0, W0p=w0').  Complex (a_y and
its couplings carry i) -- evaluate with complex arithmetic.
The closed-form solved coefficients are ~MB and numerically stiff to
emit, so this module instead carries the SMALL background coupled system
(_Mmat, _Rmat) and solves the 7x7 numerically per radius (_solve); the
row_*/alg_* wrappers return the same (coeff_H, coeff_dH, src) triples.
Args: (r, U, Up, V, Vp, W, Wp, B, G, alpha, W0, W0p).
"""

import math  # noqa: F401
import numpy as np


def _Mmat(r, U, Up, V, Vp, W, Wp, B, G, alpha, W0, W0p):
    """7x7 coefficient matrix of the unknowns (H_rr,H_xr,H_rr',H_xr',H_yy'',H_zz'',a_y'')."""
    return [
            [(1/2)*(B**2*alpha - 12*math.exp(4*V))*math.exp(-4*V)/U, (1/2)*(2*G*U*Vp + 2*G*U*Wp + G*Up)/U, 0, 0, 0, 0, 0],
            [(1/4)*(2*1j*G*U*Vp + 2*1j*G*U*Wp + 1j*G*Up)/U, (1/2)*(1j*B**2*alpha - 2*1j*U*Vp**2*math.exp(4*V) - 4*1j*U*Vp*Wp*math.exp(4*V) - 2*1j*Up*Vp*math.exp(4*V) - 1j*Up*Wp*math.exp(4*V) + 12*1j*math.exp(4*V))*math.exp(-2*V), 0, 0, 0, 0, 0],
            [(1/2)*(-4*B**2*U*Vp*alpha - B**2*Up*alpha + 12*Up*math.exp(4*V))*math.exp(-4*V)/U**2, (1/2)*(-4*G*U**2*Vp**2 - 6*G*U**2*Vp*Wp - 2*G*U**2*Wp**2 - 4*G*U*Up*Vp - 3*G*U*Up*Wp + 24*G*U - G*Up**2)/U**2, (1/2)*(B**2*alpha - 12*math.exp(4*V))*math.exp(-4*V)/U, (1/2)*(2*G*U*Vp + 2*G*U*Wp + G*Up)/U, (1/4)*(2*U*Vp + 2*U*Wp + Up)/U, (1/4)*(4*U*Vp + Up)/U, 0],
            [(1/4)*(-4*1j*G*U**2*Vp**2 - 6*1j*G*U**2*Vp*Wp - 2*1j*G*U**2*Wp**2 - 4*1j*G*U*Up*Vp - 3*1j*G*U*Up*Wp + 24*1j*G*U - 1j*G*Up**2)/U**2, (1/2)*(-2*1j*B**2*U*Vp*alpha + 2*1j*B**2*U*Wp*alpha + 1j*B**2*Up*alpha + 4*1j*U**2*Vp**3*math.exp(4*V) + 12*1j*U**2*Vp**2*Wp*math.exp(4*V) + 8*1j*U**2*Vp*Wp**2*math.exp(4*V) + 6*1j*U*Up*Vp**2*math.exp(4*V) + 10*1j*U*Up*Vp*Wp*math.exp(4*V) + 2*1j*U*Up*Wp**2*math.exp(4*V) - 24*1j*U*Vp*math.exp(4*V) - 24*1j*U*Wp*math.exp(4*V) + 2*1j*Up**2*Vp*math.exp(4*V) + 1j*Up**2*Wp*math.exp(4*V) - 12*1j*Up*math.exp(4*V))*math.exp(-2*V)/U, (1/4)*(2*1j*G*U*Vp + 2*1j*G*U*Wp + 1j*G*Up)/U, (1/2)*(1j*B**2*alpha - 2*1j*U*Vp**2*math.exp(4*V) - 4*1j*U*Vp*Wp*math.exp(4*V) - 2*1j*Up*Vp*math.exp(4*V) - 1j*Up*Wp*math.exp(4*V) + 12*1j*math.exp(4*V))*math.exp(-2*V), -1/2*1j*G, -1/2*1j*G, -B*alpha*math.exp(-2*V)],
            [-1/2*G**2 + U*Vp**2*math.exp(2*V) + 2*U*Vp*Wp*math.exp(2*V) + Up*Vp*math.exp(2*V) + (1/2)*Up*Wp*math.exp(2*V) - 12*math.exp(2*V), 2*G*U*Vp*math.exp(2*V) + G*U*Wp*math.exp(2*V) + G*Up*math.exp(2*V), -1/2*U*Vp*math.exp(2*V) - 1/2*U*Wp*math.exp(2*V) - 1/4*Up*math.exp(2*V), G*U*math.exp(2*V), 0, (1/2)*U*math.exp(2*V), 0],
            [(1/2)*(2*B**2*alpha*math.exp(2*W) - G**2*math.exp(2*V)*math.exp(2*W) + 2*U*Vp**2*math.exp(4*V)*math.exp(2*W) + 4*U*Vp*Wp*math.exp(4*V)*math.exp(2*W) + 2*Up*Vp*math.exp(4*V)*math.exp(2*W) + Up*Wp*math.exp(4*V)*math.exp(2*W) - 24*math.exp(4*V)*math.exp(2*W))*math.exp(-4*V), 3*G*U*Vp*math.exp(2*W) + G*Up*math.exp(2*W), -U*Vp*math.exp(2*W) - 1/4*Up*math.exp(2*W), G*U*math.exp(2*W), (1/2)*U*math.exp(2*W), 0, 0],
            [-1/2*1j*B*G*math.exp(-2*V)*math.exp(W), 1j*B*U*Wp*math.exp(W) + 1j*B*Up*math.exp(W), 0, 1j*B*U*math.exp(W), 0, 0, -U*math.exp(W)]]


def _Rmat(r, U, Up, V, Vp, W, Wp, B, G, alpha, W0, W0p):
    """7x8 RHS map onto (H_yy,H_yy',H_zz,H_zz',a_y,a_y',1)."""
    return [
            [-1/2*(-B**2*alpha - G**2*math.exp(2*V))*math.exp(-4*V)/U, -1/4*(2*U*Vp + 2*U*Wp + Up)/U, (1/2)*G**2*math.exp(-2*V)/U, -1/4*(4*U*Vp + Up)/U, -1j*B*G*alpha*math.exp(-4*V)/U, 0, -(-B*W0**2*alpha - U*W0p**2*alpha*math.exp(2*V))*math.exp(-4*V)/U],
            [0, (1/2)*1j*G, -1/2*1j*G*Vp + (1/2)*1j*G*Wp, (1/2)*1j*G, 0, B*alpha*math.exp(-2*V), 0],
            [-1/2*(4*B**2*U*Vp*alpha + B**2*Up*alpha + 2*G**2*U*Vp*math.exp(2*V) + G**2*Up*math.exp(2*V))*math.exp(-4*V)/U**2, -1/4*(-2*B**2*U*alpha - 2*G**2*U*math.exp(2*V) - 4*U**2*Vp**2*math.exp(4*V) - 6*U**2*Vp*Wp*math.exp(4*V) - 2*U**2*Wp**2*math.exp(4*V) - 4*U*Up*Vp*math.exp(4*V) - 3*U*Up*Wp*math.exp(4*V) + 24*U*math.exp(4*V) - Up**2*math.exp(4*V))*math.exp(-4*V)/U**2, -1/2*(2*G**2*U*Vp + G**2*Up)*math.exp(-2*V)/U**2, -1/4*(-2*B**2*U*alpha - 2*G**2*U*math.exp(2*V) - 8*U**2*Vp**2*math.exp(4*V) - 4*U**2*Vp*Wp*math.exp(4*V) - 6*U*Up*Vp*math.exp(4*V) - U*Up*Wp*math.exp(4*V) + 24*U*math.exp(4*V) - Up**2*math.exp(4*V))*math.exp(-4*V)/U**2, -(-4*1j*B*G*U*Vp*alpha - 1j*B*G*Up*alpha)*math.exp(-4*V)/U**2, -1j*B*G*alpha*math.exp(-4*V)/U, -(4*B*U*Vp*W0**2*alpha + B*Up*W0**2*alpha + 2*U**2*Vp*W0p**2*alpha*math.exp(2*V) + 2*U**2*W0p**2*Wp*alpha*math.exp(2*V) + 2*U*Up*W0p**2*alpha*math.exp(2*V))*math.exp(-4*V)/U**2],
            [0, 0, -1/2*(-1j*B**2*G*alpha - 2*1j*G*U*Vp**2*math.exp(4*V) + 1j*G*U*Vp*Wp*math.exp(4*V) + 1j*G*U*Wp**2*math.exp(4*V) - 1j*G*Up*Vp*math.exp(4*V) + 1j*G*Up*Wp*math.exp(4*V))*math.exp(-4*V)/U, -1/2*1j*G*Vp + (1/2)*1j*G*Wp, 0, -2*B*Vp*alpha*math.exp(-2*V), 0],
            [U*Vp**2*math.exp(2*V) + 2*U*Vp*Wp*math.exp(2*V) + Up*Vp*math.exp(2*V) + (1/2)*Up*Wp*math.exp(2*V) - 6*math.exp(2*V), 0, (1/2)*G**2, -1/2*U*Vp*math.exp(2*V) - U*Wp*math.exp(2*V) - 1/2*Up*math.exp(2*V), 1j*B*G*alpha*math.exp(-2*V), 0, -B*W0**2*alpha*math.exp(-2*V)],
            [-1/2*(-B**2*alpha*math.exp(2*W) - G**2*math.exp(2*V)*math.exp(2*W))*math.exp(-4*V), -3/2*U*Vp*math.exp(2*W) - 1/2*Up*math.exp(2*W), -1/2*(-B**2*alpha*math.exp(2*W) - 2*U*Vp**2*math.exp(4*V)*math.exp(2*W) - 4*U*Vp*Wp*math.exp(4*V)*math.exp(2*W) - 2*Up*Vp*math.exp(4*V)*math.exp(2*W) - Up*Wp*math.exp(4*V)*math.exp(2*W) + 12*math.exp(4*V)*math.exp(2*W))*math.exp(-4*V), 0, -1j*B*G*alpha*math.exp(-4*V)*math.exp(2*W), 0, -(-B*W0**2*alpha*math.exp(2*W) + U*W0p**2*alpha*math.exp(2*V)*math.exp(2*W))*math.exp(-4*V)],
            [-1/2*1j*B*G*math.exp(-2*V)*math.exp(W), 0, (1/2)*1j*B*G*math.exp(-2*V)*math.exp(W), 0, -G**2*math.exp(-2*V)*math.exp(W), U*Wp*math.exp(W) + Up*math.exp(W), -1j*G*W0**2*math.exp(-2*V)*math.exp(W)]]


def _solve(r, U, Up, V, Vp, W, Wp, B, G, alpha, W0, W0p):
    """X = M^{-1} R (7x8); X[i] = coeffs of (H_yy,H_yy',H_zz,H_zz',a_y,a_y',1)
    in unknown i, order (H_rr,H_xr,H_rr',H_xr',H_yy'',H_zz'',a_y'')."""
    M = np.array(_Mmat(r, U, Up, V, Vp, W, Wp, B, G, alpha, W0, W0p), dtype=complex)
    R = np.array(_Rmat(r, U, Up, V, Vp, W, Wp, B, G, alpha, W0, W0p), dtype=complex)
    return np.linalg.solve(M, R)


def row_hyy(r, U, Up, V, Vp, W, Wp, B, G, alpha, W0, W0p):
    row = _solve(r, U, Up, V, Vp, W, Wp, B, G, alpha, W0, W0p)[4]
    return ([row[0], row[2], row[4]], [row[1], row[3], row[5]], row[6])


def row_hzz(r, U, Up, V, Vp, W, Wp, B, G, alpha, W0, W0p):
    row = _solve(r, U, Up, V, Vp, W, Wp, B, G, alpha, W0, W0p)[5]
    return ([row[0], row[2], row[4]], [row[1], row[3], row[5]], row[6])


def row_ay(r, U, Up, V, Vp, W, Wp, B, G, alpha, W0, W0p):
    row = _solve(r, U, Up, V, Vp, W, Wp, B, G, alpha, W0, W0p)[6]
    return ([row[0], row[2], row[4]], [row[1], row[3], row[5]], row[6])


def alg_Hrr(r, U, Up, V, Vp, W, Wp, B, G, alpha, W0, W0p):
    row = _solve(r, U, Up, V, Vp, W, Wp, B, G, alpha, W0, W0p)[0]
    return ([row[0], row[2], row[4]], [row[1], row[3], row[5]], row[6])


def alg_Hxr(r, U, Up, V, Vp, W, Wp, B, G, alpha, W0, W0p):
    row = _solve(r, U, Up, V, Vp, W, Wp, B, G, alpha, W0, W0p)[1]
    return ([row[0], row[2], row[4]], [row[1], row[3], row[5]], row[6])


def c4_integrand(r, U, Up, V, Vp, W, Wp, B, G, alpha, W0, W0p):
    """C4 = int p1 w0^4 dr, p1 = e^{W-2V}."""
    return W0**4*math.exp(-2*V)*math.exp(W)


def x_integrand(r, U, Up, V, Vp, W, Wp, B, G, alpha, W0, W0p, ay):
    """X = int p1 bhat w0^2 dr, bhat = iG a_y (transverse)."""
    return 1j*G*W0**2*math.exp(-2*V)*math.exp(W) * ay


def pi_grav(r, U, Up, V, Vp, W, Wp, B, G, alpha, W0, W0p, hyy, hzz, ay, hrr, hxr):
    """Graviton pairing density sqrt(-g) S^{MN} h_MN (even sector);
    graviton exchange = 1/2 int pi_grav dr (plug solved fields)."""
    return (B*W0**2*hrr*math.exp(W) - B*W0**2*hyy*math.exp(W) + B*W0**2*hzz*math.exp(W) + U*W0p**2*hrr*math.exp(2*V)*math.exp(W) - U*W0p**2*hzz*math.exp(2*V)*math.exp(W))*math.exp(-2*V)

# --- provenance ----------------------------------------------------------
# Written by dk_response.py; do not edit by hand.  Verified by
# tests/test_generated_systems.py -- see backreaction/generated.py.
# generator:             dk_response.py
# generator_code_sha256: c221868f718171927a7600007a1ce21ed1e105e7c4e96fc185853e122bc543f3
# content_sha256:        79a70de78b1b1b21adca39a93afb38d96dcaa20394c0befd6d7417935a80b042
# python:                3.14
# --- provenance ----------------------------------------------------------
