"""AUTO-GENERATED by dk_stress.py -- do not edit.

Per-harmonic O(rho^2) condensate stress S_MN(r) e^{iGx} and
transverse colour-3 current J(r) on the (U,V,W) magnetic brane
(G || x, per rho^2 lambda_G).  Coord order (t,x,y,z,r).
Args: (r, U, Up, V, Vp, W, Wp, B, G, W0, W0p, BH, BHp) with
W0=w0, W0p=w0', BH=bhat, BHp=bhat'.
"""

import math  # noqa: F401


def S_tt(r, U, Up, V, Vp, W, Wp, B, G, W0, W0p, BH, BHp):
    return U*(B*(BH - W0**2) + U*W0p**2*math.exp(2*V))*math.exp(-4*V)


def S_xx(r, U, Up, V, Vp, W, Wp, B, G, W0, W0p, BH, BHp):
    return B*(BH - W0**2)*math.exp(-2*V)


def S_yy(r, U, Up, V, Vp, W, Wp, B, G, W0, W0p, BH, BHp):
    return B*(BH - W0**2)*math.exp(-2*V)


def S_zz(r, U, Up, V, Vp, W, Wp, B, G, W0, W0p, BH, BHp):
    return (-B*BH + B*W0**2 - U*W0p**2*math.exp(2*V))*math.exp(-4*V + 2*W)


def S_rr(r, U, Up, V, Vp, W, Wp, B, G, W0, W0p, BH, BHp):
    return (B*(-BH + W0**2) + U*W0p**2*math.exp(2*V))*math.exp(-4*V)/U


def S_xr(r, U, Up, V, Vp, W, Wp, B, G, W0, W0p, BH, BHp):
    return -1j*B*BHp*math.exp(-2*V)/G


def J_transverse(r, U, Up, V, Vp, W, Wp, B, G, W0, W0p, BH, BHp):
    return G**2*W0**2*math.exp(-2*V + W)

# --- provenance ----------------------------------------------------------
# Written by dk_stress.py; do not edit by hand.  Verified by
# tests/test_generated_systems.py -- see backreaction/generated.py.
# generator:             dk_stress.py
# generator_code_sha256: 07863eafa3404adc47cd84ead57a9ef13b54add4d8245fc7886250fea8eb6d4b
# content_sha256:        16b92eb784c7ab979d7df6fbed6df2323e702dc555aaa02dd5ee1f910b93caf1
# python:                3.14
# --- provenance ----------------------------------------------------------
