"""AUTO-GENERATED by dk_uniform.py -- do not edit.

Uniform (G = 0) response of the D'Hoker-Kraus magnetic brane
  ds^2 = -U dt^2 + dr^2/U + e^{2V}(dx^2+dy^2) + e^{2W} dz^2,  A^3_y = Bx,
to the lattice-averaged condensate stress, gauge H_tt = 0:
  h = diag(0, e^{2V} H_xx, e^{2V} H_xx, e^{2W} H_zz, H_rr/U).
Unknowns (H_rr, H_rr', H_xx'', H_zz'') from the rows {rr, d/dr rr, xx,
zz}:  M . unk = R . (H_xx, H_xx', H_zz, H_zz', 1), solved numerically
per radius (_solve).  The source carries the explicit factor alpha.
Args: (r, U, Up, V, Vp, W, Wp, B, alpha, W0, W0p).
"""

import math  # noqa: F401
import numpy as np


def _Mmat(r, U, Up, V, Vp, W, Wp, B, alpha, W0, W0p):
    """4x4 coefficients of (H_rr, H_rr', H_xx'', H_zz'')."""
    return [
            [(1/2)*B**2*alpha*math.exp(-4*V)/U - 6/U, 0, 0, 0],
            [-2*B**2*Vp*alpha*math.exp(-4*V)/U - 1/2*B**2*Up*alpha*math.exp(-4*V)/U**2 + 6*Up/U**2, (1/2)*B**2*alpha*math.exp(-4*V)/U - 6/U, Vp + Wp + (1/2)*Up/U, Vp + (1/4)*Up/U],
            [U*Vp**2*math.exp(2*V) + 2*U*Vp*Wp*math.exp(2*V) + Up*Vp*math.exp(2*V) + (1/2)*Up*Wp*math.exp(2*V) - 12*math.exp(2*V), -1/2*U*Vp*math.exp(2*V) - 1/2*U*Wp*math.exp(2*V) - 1/4*Up*math.exp(2*V), (1/2)*U*math.exp(2*V), (1/2)*U*math.exp(2*V)],
            [B**2*alpha*math.exp(-4*V)*math.exp(2*W) + U*Vp**2*math.exp(2*W) + 2*U*Vp*Wp*math.exp(2*W) + Up*Vp*math.exp(2*W) + (1/2)*Up*Wp*math.exp(2*W) - 12*math.exp(2*W), -U*Vp*math.exp(2*W) - 1/4*Up*math.exp(2*W), U*math.exp(2*W), 0]]


def _Rmat(r, U, Up, V, Vp, W, Wp, B, alpha, W0, W0p):
    """4x5 RHS map onto (H_xx, H_xx', H_zz, H_zz', 1)."""
    return [
            [B**2*alpha*math.exp(-4*V)/U, -Vp - Wp - 1/2*Up/U, 0, -Vp - 1/4*Up/U, B*W0**2*alpha*math.exp(-4*V)/U + W0p**2*alpha*math.exp(-2*V)],
            [-4*B**2*Vp*alpha*math.exp(-4*V)/U - B**2*Up*alpha*math.exp(-4*V)/U**2, B**2*alpha*math.exp(-4*V)/U + 2*Vp**2 + 3*Vp*Wp + Wp**2 + 2*Up*Vp/U + (3/2)*Up*Wp/U - 12/U + (1/2)*Up**2/U**2, 0, (1/2)*B**2*alpha*math.exp(-4*V)/U + 2*Vp**2 + Vp*Wp + (3/2)*Up*Vp/U + (1/4)*Up*Wp/U - 6/U + (1/4)*Up**2/U**2, -4*B*Vp*W0**2*alpha*math.exp(-4*V)/U - B*Up*W0**2*alpha*math.exp(-4*V)/U**2 - 2*Vp*W0p**2*alpha*math.exp(-2*V) - 2*W0p**2*Wp*alpha*math.exp(-2*V) - 2*Up*W0p**2*alpha*math.exp(-2*V)/U],
            [-1/2*B**2*alpha*math.exp(-2*V) + U*Vp**2*math.exp(2*V) + 2*U*Vp*Wp*math.exp(2*V) + Up*Vp*math.exp(2*V) + (1/2)*Up*Wp*math.exp(2*V) - 6*math.exp(2*V), -U*Vp*math.exp(2*V) - 1/2*U*Wp*math.exp(2*V) - 1/2*Up*math.exp(2*V), 0, -1/2*U*Vp*math.exp(2*V) - U*Wp*math.exp(2*V) - 1/2*Up*math.exp(2*V), -B*W0**2*alpha*math.exp(-2*V)],
            [B**2*alpha*math.exp(-4*V)*math.exp(2*W), -3*U*Vp*math.exp(2*W) - Up*math.exp(2*W), (1/2)*B**2*alpha*math.exp(-4*V)*math.exp(2*W) + U*Vp**2*math.exp(2*W) + 2*U*Vp*Wp*math.exp(2*W) + Up*Vp*math.exp(2*W) + (1/2)*Up*Wp*math.exp(2*W) - 6*math.exp(2*W), 0, B*W0**2*alpha*math.exp(-4*V)*math.exp(2*W) - U*W0p**2*alpha*math.exp(-2*V)*math.exp(2*W)]]


def _solve(r, U, Up, V, Vp, W, Wp, B, alpha, W0, W0p):
    """X = M^{-1} R (4x5); X[i] = coeffs of (H_xx, H_xx', H_zz, H_zz', 1)
    in unknown i, order (H_rr, H_rr', H_xx'', H_zz'')."""
    M = np.array(_Mmat(r, U, Up, V, Vp, W, Wp, B, alpha, W0, W0p), dtype=float)
    R = np.array(_Rmat(r, U, Up, V, Vp, W, Wp, B, alpha, W0, W0p), dtype=float)
    return np.linalg.solve(M, R)


def pi_density(r, U, Up, V, Vp, W, Wp, B, alpha, W0, W0p, Hxx, Hzz, Hrr):
    """sqrt(-g) S^{MN} h_MN in the gauge H_tt = 0 (= -2(dP w0'^2 - dQ w0^2))."""
    return B*Hrr*W0**2*math.exp(-2*V)*math.exp(W) - 2*B*Hxx*W0**2*math.exp(-2*V)*math.exp(W) + B*Hzz*W0**2*math.exp(-2*V)*math.exp(W) + Hrr*U*W0p**2*math.exp(W) - Hzz*U*W0p**2*math.exp(W)

# --- provenance ----------------------------------------------------------
# Written by dk_uniform.py; do not edit by hand.  Verified by
# tests/test_generated_systems.py -- see backreaction/generated.py.
# generator:             dk_uniform.py
# generator_code_sha256: 9871202ab7f088b07ce51aa219be0787364f837b36f02f3a13232205db330603
# content_sha256:        da6120c9872911be9c68c7fcbc02ffaef531205ff974e70ebba92a5c1e3827ac
# python:                3.14
# --- provenance ----------------------------------------------------------
