"""AUTO-GENERATED by dk_zeromode.py -- do not edit.

Linearised SU(2) W zero-mode (polarised LLL) radial operator on the
general diagonal magnetic brane
    ds^2 = -U dt^2 + dr^2/U + e^{2V}(dx^2+dy^2) + e^{2W} dz^2,
background A^3_y = B x.  Sturm-Liouville form
    (p w')' + q w = 0   <=>   p w'' + p1 w' + q w = 0,
    p = U e^{W},  p1 = e^{W}(U' + U W'),  q = B e^{W-2V},
eigenvalue B, weight p, norm density rho = e^{W-2V}
    (analogue of J_2 = int rho w^2 dr).
Horizon regularity (U(r_p)=0):  w'(r_p) = horizon_slope * w(r_p).
Boundary (r->oo): source c0 at r^0, source-free c0 = 0; vev at r^{-2}.
"""

import math  # noqa: F401


def sl_p(r, U, Up, V, Vp, W, Wp, B):
    return U*math.exp(W)


def sl_p1(r, U, Up, V, Vp, W, Wp, B):
    return (U*Wp + Up)*math.exp(W)


def sl_q(r, U, Up, V, Vp, W, Wp, B):
    return B*math.exp(-2*V + W)


def sl_rho(r, U, Up, V, Vp, W, Wp, B):
    return math.exp(-2*V + W)


def horizon_slope(r, U, Up, V, Vp, W, Wp, B):
    """w'(r_p)/w(r_p) at a regular horizon (U -> 0)."""
    return -B*math.exp(-2*V)/Up

# --- provenance ----------------------------------------------------------
# Written by dk_zeromode.py; do not edit by hand.  Verified by
# tests/test_generated_systems.py -- see backreaction/generated.py.
# generator:             dk_zeromode.py
# generator_code_sha256: 1171c2226c9ec3ff2afac8996d9874fafe4fc50af70e81105a7ba04364f1309f
# content_sha256:        d1e5614cb661073b20408493ea2ecc005e75152f1b61109ee933ceb2d7d3790f
# python:                3.14
# --- provenance ----------------------------------------------------------
