"""AUTO-GENERATED by g0.py -- do not edit.

G = 0 (homogeneous) sector, alpha = 1, sources kept separate:
each row function returns (coeff_H, coeff_dH, src_B2, src_r2)
so that  LHS = coeff_H . H + coeff_dH . H' + q2*src_B2 + r2*src_r2
with q2 = B^2-source unit and r2 = rho^2-source unit.

Algebraic gauge Htt = 0, field order (Hxx, Hzz):
    Hxx'' = g0a_row_xx,  Hzz'' = g0a_row_zz,  Huu = g0a_huu [algebraic]
Radial gauge Huu = 0, field order (Htt, Hxx, Hzz):
    H_i'' = g0r_row_*,  constraint 0 = g0r_constraint
Decoupled invariant I_d = Hxx - Hzz:
    f Id'' + (f' - 3f/u) Id' = q2*Sd_B2 + r2*Sd_r2 (g0_id_source)
"""

import math  # noqa: F401


def g0a_row_xx(u, B, u_H, W0, W0p):
    coeff_H = [0, 0]
    coeff_dH = [(-11*u**8 + 12*u**4*u_H**4 - 9*u_H**8)/(3*u**9 - 3*u*u_H**8), (-4*u**7 + 12*u**3*u_H**4)/(3*u**8 - 3*u_H**8)]
    src_B2 = (-2*u**6*u_H**4 + 6*u**2*u_H**8)/(3*u**8 - 3*u_H**8)
    src_r2 = (4*B*W0**2*u**6*u_H**4 - 12*B*W0**2*u**2*u_H**8 - 6*W0p**2*u**10 + 6*W0p**2*u**2*u_H**8)/(3*u**8 - 3*u_H**8)
    return coeff_H, coeff_dH, src_B2, src_r2


def g0a_row_zz(u, B, u_H, W0, W0p):
    coeff_H = [0, 0]
    coeff_dH = [(-8*u**7 + 24*u**3*u_H**4)/(3*u**8 - 3*u_H**8), (-7*u**8 - 9*u_H**8)/(3*u**9 - 3*u*u_H**8)]
    src_B2 = -8*u**6*u_H**4/(3*u**8 - 3*u_H**8)
    src_r2 = 16*B*W0**2*u**6*u_H**4/(3*u**8 - 3*u_H**8)
    return coeff_H, coeff_dH, src_B2, src_r2


def g0a_huu(u, B, u_H, W0, W0p):
    coeff_H = [0, 0]
    coeff_dH = [(1/6)*(u**5 - 3*u*u_H**4)/u_H**4, (1/12)*(u**5 - 3*u*u_H**4)/u_H**4]
    src_B2 = (1/12)*u**4
    src_r2 = (1/6)*(-B*W0**2*u**4*u_H**4 + W0p**2*u**8 - W0p**2*u**4*u_H**4)/u_H**4
    return coeff_H, coeff_dH, src_B2, src_r2


def g0_id_source(u, B, u_H, W0, W0p):
    src_B2 = -2*u**2
    src_r2 = 12*B*W0**2*u**11/(3*u**9 - 3*u*u_H**8) - 12*B*W0**2*u**3*u_H**8/(3*u**9 - 3*u*u_H**8) + 6*W0p**2*u**15/(3*u**9*u_H**4 - 3*u*u_H**12) - 6*W0p**2*u**11/(3*u**9 - 3*u*u_H**8) - 6*W0p**2*u**7*u_H**4/(3*u**9 - 3*u*u_H**8) + 6*W0p**2*u**3*u_H**8/(3*u**9 - 3*u*u_H**8)
    return src_B2, src_r2


ID_B2_HORIZON_COEFF = 2.056167583560e-01  # I_d(u_H) per alpha B^2 u_H^2... exact quadrature, u_H = 1


def g0_j_channel(u, B, u_H, W0, W0p):
    """V_J' = c V_J + src (V_J = 2 Hxx' + Hzz'), u_H = 1."""
    c = (3 - 5*u**4)/(u**5 + u)
    src_B2 = -4*u**2/(u**4 + 1)
    src_r2 = 8*B*W0**2*u**2/(u**4 + 1) - 4*W0p**2*u**2
    return c, src_B2, src_r2


DS_FIXED_T_B2 = 0.25  # exact: ds|_T per alpha B^2 (u_H = 1)

# --- provenance ----------------------------------------------------------
# Written by g0.py; do not edit by hand.  Verified by
# tests/test_generated_systems.py -- see backreaction/generated.py.
# generator:             g0.py
# generator_code_sha256: 26e0fb9166116fd3d2639345fd01a4d7d1461c053108ac90c1e7a671a98763b9
# content_sha256:        d6f1299362ea7283ce55c973c81d65ec8f7af0f43f8055604558b36441fddc51
# python:                3.14
# --- provenance ----------------------------------------------------------
