"""AUTO-GENERATED by gauge_invariant.py -- do not edit.

Algebraic gauge Htt = Hxx = 0 (fields are gauge invariants).
Field order: (Hyy, Hzz); per rho^2 lambda_G, alpha = 1.
Each function returns (coeff_H[2], coeff_dH[2], src):
    Hyy'' = row_yy . (H, dH) + src,   Hzz'' = row_zz . (H, dH) + src
    Huu   = huu_expr . (H, dH) + src    [algebraic]
    Hxu   = hxu_expr . (H, dH) + src    [algebraic]
"""

import math  # noqa: F401


def row_yy(u, B, u_H, G, W0, W0p, BH, BHp):
    coeff_H = [-G**2*u_H**4/(u**4 - u_H**4), 0]
    coeff_dH = [(-u**12 + 15*u**8*u_H**4 - 7*u**4*u_H**8 + 9*u_H**12)/(u**13 - 3*u**9*u_H**4 - u**5*u_H**8 + 3*u*u_H**12), 16*u**3*u_H**4/(u**8 - 2*u**4*u_H**4 - 3*u_H**8)]
    src = (4*B*BH*G**2*u**10*u_H**4 - 36*B*BH*G**2*u**2*u_H**12 - 96*B*BHp*u**9*u_H**4 + 96*B*BHp*u**5*u_H**8 - 4*B*G**2*W0**2*u**10*u_H**4 + 36*B*G**2*W0**2*u**2*u_H**12 + 2*G**2*W0p**2*u**14 - 14*G**2*W0p**2*u**10*u_H**4 + 30*G**2*W0p**2*u**6*u_H**8 - 18*G**2*W0p**2*u**2*u_H**12)/(3*G**2*u**12 - 9*G**2*u**8*u_H**4 - 3*G**2*u**4*u_H**8 + 9*G**2*u_H**12)
    return coeff_H, coeff_dH, src


def row_zz(u, B, u_H, G, W0, W0p, BH, BHp):
    coeff_H = [0, -G**2*u_H**4/(u**4 - u_H**4)]
    coeff_dH = [16*u**3*u_H**4/(u**8 - 2*u**4*u_H**4 - 3*u_H**8), (-u**12 + 15*u**8*u_H**4 - 7*u**4*u_H**8 + 9*u_H**12)/(u**13 - 3*u**9*u_H**4 - u**5*u_H**8 + 3*u*u_H**12)]
    src = (-8*B*BH*G**2*u**10*u_H**4 + 24*B*BH*G**2*u**6*u_H**8 - 96*B*BHp*u**9*u_H**4 + 96*B*BHp*u**5*u_H**8 + 8*B*G**2*W0**2*u**10*u_H**4 - 24*B*G**2*W0**2*u**6*u_H**8 + 8*G**2*W0p**2*u**14 - 32*G**2*W0p**2*u**10*u_H**4 + 24*G**2*W0p**2*u**6*u_H**8)/(3*G**2*u**12 - 9*G**2*u**8*u_H**4 - 3*G**2*u**4*u_H**8 + 9*G**2*u_H**12)
    return coeff_H, coeff_dH, src


def huu_expr(u, B, u_H, G, W0, W0p, BH, BHp):
    coeff_H = [0, 0]
    coeff_dH = [(-u**5 + u*u_H**4)/(u**4 - 3*u_H**4), (-u**5 + u*u_H**4)/(u**4 - 3*u_H**4)]
    src = (2*B*BHp*u**7 - 2*B*BHp*u**3*u_H**4)/(G**2*u**4 - 3*G**2*u_H**4)
    return coeff_H, coeff_dH, src


def hxu_expr(u, B, u_H, G, W0, W0p, BH, BHp):
    coeff_H = [G*u*u_H**4/(2*u**4 - 6*u_H**4), G*u*u_H**4/(2*u**4 - 6*u_H**4)]
    coeff_dH = [(-u**8 - 6*u**4*u_H**4 + 3*u_H**8)/(2*G*u**8 - 12*G*u**4*u_H**4 + 18*G*u_H**8), (-u**8 - 6*u**4*u_H**4 + 3*u_H**8)/(2*G*u**8 - 12*G*u**4*u_H**4 + 18*G*u_H**8)]
    src = (-B*BH*G**2*u**7*u_H**4 + 3*B*BH*G**2*u**3*u_H**8 + 12*B*BHp*u**6*u_H**4 - 12*B*BHp*u**2*u_H**8 + B*G**2*W0**2*u**7*u_H**4 - 3*B*G**2*W0**2*u**3*u_H**8 - G**2*W0p**2*u**11 + 4*G**2*W0p**2*u**7*u_H**4 - 3*G**2*W0p**2*u**3*u_H**8)/(G**3*u**8 - 6*G**3*u**4*u_H**4 + 9*G**3*u_H**8)
    return coeff_H, coeff_dH, src

# --- provenance ----------------------------------------------------------
# Written by gauge_invariant.py; do not edit by hand.  Verified by
# tests/test_generated_systems.py -- see backreaction/generated.py.
# generator:             gauge_invariant.py
# generator_code_sha256: 58bbd1288407926b89ab3de98930221ce297a0b43c3dc503d7f305044bd4b367
# content_sha256:        06606a81f957307fa7bb17ed2d16d330b98420b7c8ca339f4baca4979b01dc06
# python:                3.14
# --- provenance ----------------------------------------------------------
